baseURL = "https://awsomename.github.io"
languageCode = "en-us"
title = "Lc92.Blogs"
theme = "kube"
description = "Welcome, friends"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "spongeBob" # add your company name
  github = "AwsomeName" # add your github profile name
  twitter = "" # add your twitter profile
  email = "liuchang.hit.cs@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
